version: '3.8'

services:
  # ===================== DATABASE =====================
  mysql:
    image: mysql:8.0
    container_name: grouppay-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 9873
      MYSQL_DATABASE: grouppay
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # ===================== CACHE =====================
  redis:
    image: redis:alpine
    container_name: grouppay-redis
    restart: always
    ports:
      - "6379:6379"

  # ===================== MESSAGE BROKER =====================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: grouppay-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: grouppay-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mysql_data:
